name: CI

on:
  push:

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.5.3
            otp: 19.3.6.13
            os: ubuntu-16.04
          - elixir: 1.5.3
            otp: 19.3.6.13
            os: ubuntu-18.04
          - elixir: 1.5.3
            otp: 19.3.6.13
            os: ubuntu-20.04
          - elixir: 1.11.3
            otp: 23.2.5
            os: ubuntu-16.04
          - elixir: 1.11.3
            otp: 23.2.5
            os: ubuntu-18.04
          - elixir: 1.11.3
            otp: 23.2.5
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix deps.get --only test
      - run: mix test
